resource_group_name     = "taskboard-rg"
resource_group_location = "Spain Central"
sql_database_name       = "taskboard-db"
firewall_rule_name      = "AllowAzureServices"
dotnet_version          = "8.0"
github_repo_url         = "https://github.com/Dimitar-Peev/TaskBoard-Terraform"
github_branch           = "main"
