name: 'Provision Service Principal'

on:
  workflow_run:
    workflows: ["Provision Terraform Backend"]
    types:
      - completed
  workflow_dispatch:

env:
  ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_client_id:       ${{ secrets.AZURE_CLIENT_ID }}

jobs:
  provision-sp:
    name: 'Provision Service Principal'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"

      - name: Terraform Init
        working-directory: terraform-sp
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform-sp
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform-sp
        run: terraform apply -auto-approve tfplan

      - name: Show Outputs
        working-directory: terraform-sp
        run: terraform output